name: Metrics
on:
  # Update every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual run
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dotacow
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Amman
          
          # ---  Languages Plugin Config ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          
   
          extras_css: |
            svg { background-color: #282828; border-radius: 5px; }
            .header { fill: #ebdbb2 !important; }
            .stat { fill: #fabd2f !important; } 
            .field { fill: #b8bb26 !important; }
            h1, h2, h3 { color: #fb4934 !important; }
            .content { color: #ebdbb2 !important; }
