name: Metrics
on:
  # Update every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual run
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dotacow
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Amman
          
          # This saves the image to your repo
          filename: github-metrics.svg
          
          # Gruvbox Dark Theme Customization
          config_style: |
            body { background-color: #282828; }
            .header { fill: #ebdbb2; }
            .stat { fill: #d79921; } 
            .field { fill: #b8bb26; }
            h1, h2, h3 { color: #fb4934; }
